# Site settings
title: Helga Jiang
email: hhjiang@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Helga Jiang.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: http://helgajiang.github.io/ # the base hostname & protocol for your site
twitter_username: helgajiang
github_username:  helgajiang

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
